### ISSUE TITLE
Remove TODO and clean up associated UT

### ISSUE THREAD

**Issue by skliper** [nasa/DS#40]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [README file](https://github.com/nasa/DS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
https://github.com/nasa/DS/blob/237385bca3be9cf28324a9aa05f94801e9bfb4b8/unit-test/ds_file_tests.c#L1175-L1215

**Describe the solution you'd like**
Clean up the test, remove TODO

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC
